export default[
    {
        path:"/index",
        name:"首页",
        component:()=>import("../views/index.vue"),
    },
    {
        path:"/food",
        name:"食品类",
        component:()=>import("../components/index/food.vue")
    },
    {
        path:"/tableware",
        name:"食具类",
        component:()=>import("../components/index/tableware.vue")
    },
    {
        path:"/enlightened",
        name:"启智类",
        component:()=>import("../components/index/enlightened.vue")
    },
    {
        path:"/cloth",
        name:"服装及布类",
        component:()=>import("../components/index/cloth.vue")
    },
    {
        path:"/furniture",
        name:"家具类",
        component:()=>import("../components/index/furniture.vue")
    },
    {
        path:"/electronic",
        name:"电子电器类",
        component:()=>import("../components/index/electronic.vue")
    },
]